<a href="https://colab.research.google.com/github/JJuwan/2025-1-myclass-BDA/blob/main/inclass/02w_B_0312_pandas_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [122]:
import numpy as np
import pandas as pd

s = ['희빈', '수영', '현수', '지호', '지민']
p = pd.Series([99, 84, 92 ,62, 78], index=s)
p

희빈    99
수영    84
현수    92
지호    62
지민    78
dtype: int64

In [123]:
p.name = '수학성적'
p.index.name = '이름'
p

이름
희빈    99
수영    84
현수    92
지호    62
지민    78
Name: 수학성적, dtype: int64

In [124]:
p.sort_values()

이름
지호    62
지민    78
수영    84
현수    92
희빈    99
Name: 수학성적, dtype: int64

In [125]:
p.sort_values(ascending=False)

이름
희빈    99
현수    92
수영    84
지민    78
지호    62
Name: 수학성적, dtype: int64

In [126]:
p.sort_index()

이름
수영    84
지민    78
지호    62
현수    92
희빈    99
Name: 수학성적, dtype: int64

In [127]:
p.sort_index(ascending=False)

이름
희빈    99
현수    92
지호    62
지민    78
수영    84
Name: 수학성적, dtype: int64

## 시리즈의 기본 통계 함수

In [128]:
print(p.max())
print(p.min())
print(p.mean())
print(p.median())
print(p.count())
print(p.size)

99
62
83.0
84.0
5
5

In [129]:
p.describe()

count     5.000000
mean     83.000000
std      14.177447
min      62.000000
25%      78.000000
50%      84.000000
75%      92.000000
max      99.000000
Name: 수학성적, dtype: float64

In [130]:
s = pd.Series([3, 1, 1, 2, None, np.nan, 4, 6, 6, np.nan])

In [131]:
s.values

array([ 3.,  1.,  1.,  2., nan, nan,  4.,  6.,  6., nan])

In [132]:
s.count()

7

In [133]:
s.value_counts()
#s.value_counts(dropna=False)

1.0    2
6.0    2
3.0    1
2.0    1
4.0    1
Name: count, dtype: int64

In [134]:
s.value_counts(dropna=False)

NaN    3
1.0    2
6.0    2
3.0    1
2.0    1
4.0    1
Name: count, dtype: int64

In [135]:
s.value_counts(sort=False, dropna=False)

3.0    1
1.0    2
2.0    1
NaN    3
4.0    1
6.0    2
Name: count, dtype: int64

In [136]:
s.value_counts(bins=4)

(0.994, 2.25]    3
(4.75, 6.0]      2
(2.25, 3.5]      1
(3.5, 4.75]      1
Name: count, dtype: int64

In [137]:
s.value_counts(bins=4, sort=False)

(0.994, 2.25]    3
(2.25, 3.5]      1
(3.5, 4.75]      1
(4.75, 6.0]      2
Name: count, dtype: int64

In [138]:
s.value_counts(bins=[0.5, 3.5, 6.5], sort=False)

(0.499, 3.5]    4
(3.5, 6.5]      3
Name: count, dtype: int64

##데이터프레임 다루기

In [139]:
import pandas as pd

df = pd.DataFrame([10, 20, 30, 40, 50])
df

    0
0  10
1  20
2  30
3  40
4  50

In [157]:
list=('abc')

In [158]:
df = pd.DataFrame([[1, 2, 3], [10, 20, 30], [100, 200, 300]],
                  index=list('abc'), columns=list('ABC'))
df

TypeError: 'str' object is not callable

In [ ]:
df = pd.DataFrame([[1, 2, 3],[10, 20, 30], [100, 200, 300]],
                  index=list('abc')), columns=list('ABC')
df

In [142]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [143]:
df.columns

RangeIndex(start=0, stop=1, step=1)

In [144]:
df1 = pd.DataFrame((np.arange(12)).reshape(3, 4))
df1

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [145]:
df1 = pd.DataFrame(np.random.randint(1, 46, (5, 6)))
df1

    0   1   2   3   4   5
0  26  31  29  13   9  41
1  38  31  25   9   7  37
2  36  44  10   1   6  38
3  38  15   3  11  19  24
4  20  26  24  44  45  36

In [146]:
df1 = pd.DataFrame(np.random.random((5, 3)))
df1

          0         1         2
0  0.356619  0.176487  0.524921
1  0.447643  0.137047  0.602190
2  0.929705  0.766582  0.254022
3  0.522124  0.022896  0.607325
4  0.248140  0.764269  0.732319

In [147]:
df = pd.DataFrame({'numbers': [1, 2, 3],
                   'colors': ['red', 'white', 'blue']})
df

   numbers colors
0        1    red
1        2  white
2        3   blue

In [148]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [149]:
df.columns

Index(['numbers', 'colors'], dtype='object')

In [150]:
df = pd.DataFrame({'국어': [82, 76, 67], '수학': [99, 87, 78]},
                  index=['김국진', '신영희', '이길순'])
df

     국어  수학
김국진  82  99
신영희  76  87
이길순  67  78

In [151]:
df.index

Index(['김국진', '신영희', '이길순'], dtype='object')

In [152]:
df.columns

Index(['국어', '수학'], dtype='object')

In [153]:
cources = pd.Series(["Spark", "PySpark", "Hadoop"], name='courses')
cources

0      Spark
1    PySpark
2     Hadoop
Name: courses, dtype: object

In [154]:
 fees = pd.Series([250000, 300000, 200000], name='fees')

In [155]:
df = pd.DataFrame({courses.name: courses, fees.name: fees})
df

NameError: name 'courses' is not defined

In [ ]:
cources = pd.Series(["Spark", "PySpark", "Hadoop"], name='courses')
fees = pd.Series([250000, 300000, 200000], name='fees')

df = pd.concat([courses, fees])
df

In [ ]:
df.T

In [ ]:
df = pd.DataFrame()
df

In [ ]:
cources = pd.Series(["Spark", "PySpark", "Hadoop"], name='courses')
df[courses.name] = courses
df

In [156]:
datas = pd.date_range("20250302", periods=6)
dates

NameError: name 'dates' is not defined

안해 ㅆㅂ